-- AlterTable
ALTER TABLE `supplier` ADD COLUMN `discount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `evidence` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `ppn` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `price` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `quantity` INTEGER NOT NULL DEFAULT 0;
